### ISSUE TITLE
Dragging maximized windows

### ISSUE THREAD

**Issue by dffischer** [Thoma5/gnome-shell-extension-bottompanel#2]
Maximized windows can be unmaximized by starting a drag motion from the top bar. When the bar is moved to the bottom with this extension, this does not work as expected. Instead of following the mouse cursor, the window remains pinned to the top of the screen, albeit unmaximized.

Steps to reproduce:
- Open any window.
- Maximize it.
- Place the mouse on an empty space of the panel.
- Press the mouse button and keep it down.
- Drag up.
  Until the mouse button is released, the horizontal position follows the movements of the mouse, but vertically, it stays at the upper edge of the screen.

**Comment by tuxor1337** [comment]
It's not so clear how you would want this to work. Do you want the pointer to jump somewhere to the top? Nobody wants jumping cursors... Do you want the window to jump to the cursor?

Whatever you desire - the behaviour when moving maximized windows is fixed in mutter: When the grab operation is started, the window is unmaximized and positioned at the top of the screen, following the cursor movements. This extension can't change this behavior.

There's another reason why this extension will never be able to handle this: The original panel itself handles what happens when it is clicked. There's no way you could change this if not by recompiling GNOME.

**Comment by dffischer** [comment]
> Nobody wants jumping cursors...

Correct. So the more sensible behaviour would be the second alternative, placing the titlebar of the moving window under the cursor as soon as it gets visible. Having the panel drag hardcoded into mutter makes this hard to change, indeed. I do not know whether the extension could hook into unmaximization events of all windows, adjusting their placement.

**Comment by Thoma5** [comment]
tuxor1337 described the problem well. Even if there is a way to fix this with a gnome extension, it isn't worth the time, it would take to find a way to fix it, as we don't know how long it would work then, since the gnome shell is changing a lot every two Versions. It's sad that there is hardly any documentation for the gnome shell. Everything I've done so far with it was playing around with the looking glass or looked into the source of other extensions.
